### ISSUE TITLE
是否可以考虑支持下面的场景

### ISSUE THREAD

**Issue by wzi90921** [yuantiku/YTKKeyValueStore#18]
场景：
一个微博有很多个评论；显示该微博的所有评论；需要传递微博ID;
如果要删除某个评论，需要传递的是评论ID.

是否可以考虑支持上面的场景呢。

**Comment by lancy** [comment]
目前开源的版本是不支持的，我们内部有类似场景的解决方案但还未开源

目前可以通过deleteByIdPrefix来达到批量删除的功能，也可以考虑把所有数据取出来，找出需要删除的ID再删除

这个项目的定位是简单的数据存取，如果类似需求较多，建议直接使用FMDB。
