### ISSUE TITLE
为何不将操作成功与否，作为返回值返回呢?

### ISSUE THREAD

**Issue by LiZunYuan** [yuantiku/YTKKeyValueStore#19]
比如
- (void)putObject:(id)object withId:(NSString *)objectId intoTable:(NSString *)tableName 

改成 

- (BOOL)putObject:(id)object withId:(NSString *)objectId intoTable:(NSString *)tableName 

会不会更好一点

**Comment by tangqiaoboy** [comment]
还是为了简单设计，我们在使用中没有遇到这种需求。出错只是打一个log。

如果出错是一个常态，需要上层处理的话，我感觉可能设计得不好。
另外如果上层真的要处理出错，那么一个bool值可能还不够，还需要传一个 NSError 对象进去，可能才是一个完整的设计。

所以，我并不打算这么改Api，不过你可以自己fork出一份来改，毕竟也不需要改几行代码就可以。

2015-07-31 16:33 GMT+08:00 LiZunYuan <notifications@github.com>:
