### ISSUE TITLE
数据库的打开与关闭

### ISSUE THREAD

**Issue by aceprince** [yuantiku/YTKKeyValueStore#30]
你好，在实际使用中，我们需要考虑数据库的打开与关闭操作吗？

**Comment by tangqiaoboy** [comment]
关闭数据库的话，我们好象提供了一个 close 方法吧？

2016-08-17 11:23 GMT+08:00 aceprince <notifications@github.com>:

**Comment by aceprince** [comment]
我知道有一个close方法。我意思是，我在每次执行完库的操作时需不需手动调用close，来管理库的打开与关闭。还是说我不需要关心，看你demo里面也没有调用。

**Comment by tangqiaoboy** [comment]
一般不用关心数据库的关闭。不南非要手动调用 close。

2016-08-17 15:25 GMT+08:00 aceprince <notifications@github.com>:

**Comment by aceprince** [comment]
OK，非常感谢~
