### ISSUE TITLE
Pod 下来的代码不同步？

### ISSUE THREAD

**Issue by ShannonChenCHN** [yuantiku/YTKKeyValueStore#36]
为什么在 Podfile 中写
 pod 'YTKKeyValueStore', :git => 'https://github.com/yuantiku/YTKKeyValueStore.git'
与
 pod 'YTKKeyValueStore', '~> 0.1.2’ 
获取到的代码不同？

**Comment by fishmwei** [comment]
一个取当前库上最新代码， 一个取最近满足条件('~> 0.1.2’)的版本发布时标签的代码  不一样是正常的。
